[package]
name = "iptm"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
regex = "1"
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1", features = ["v4", "serde"] }
